language: ruby
dist: xenial
services:
  - postgresql
cache:
  directories:
    - gemfiles/vendor/bundle
    - /home/travis/.rvm/gems/ruby-2.5.7
    - /home/travis/.rvm/gems/ruby-2.6.5
    - /home/travis/.rvm/gems/ruby-2.7.1
# Source: <https://docs.travis-ci.com/user/languages/ruby/#bundler-20>
before_install: scripts/ci/ensure-bundler-1-x
script: "bundle exec rake"
env:
  matrix:
    - DATABASE_ADAPTER=sqlite3
    - DATABASE_ADAPTER=postgresql
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.1
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_4_2.gemfile
branches:
  only:
    - master
